[workspace]
authors = ["elaprelleboucher"]
channels = ["conda-forge"]
name = "ernests-template"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]

# Python
python = "*"
numpy = "*"
lark = "*"

# Développement
autopep8 = "*"
coverage = "*"
pytest = "*"
snakeviz = "*"
tqdm = "*"

[tasks]

# Mono
main = "python main.py"
config = "python config.py"
format = "autopep8 --in-place --recursive ./"
go = "python main_dev.py"
test = "pytest engine/test"
testx = "pytest -s -x engine"
print_test = "pytest -s engine"

# Multi
coverage = {depends-on = ["_cover_get", "_cover_show"]}
perf = {depends-on = ["_perf_get", "_perf_show"]}
validate = {depends-on = ["format", "test", "main"]}

_cover_get = "coverage run --source=engine -m pytest"
_cover_show = "coverage html"
_perf_get = "python -m cProfile -o profil.prof main_perf.py"
_perf_show = "snakeviz profil.prof"
